
[loot]
	#Set to true to allow fake players to generate champion loot
	fakeLoot = false
	#Set the source of champion mob drops
	#Allowed Values: CONFIG, LOOT_TABLE, CONFIG_AND_LOOT_TABLE
	lootSource = "CONFIG"
	#List of loot drops from champions if sourced from config
	#Format: [tier];[modid:name];[amount];[enchant(true/false)];[weight]
	lootDrops = ["2;yuusha:grief_seed;1;false;1", "3;yuusha:grief_seed;1;false;1", "4;yuusha:grief_seed;1;false;1", "5;yuusha:grief_seed;1;false;1", "6;yuusha:grief_seed;1;false;1", "7;yuusha:grief_seed;1;false;1", "8;yuusha:grief_seed;1;false;1", "9;yuusha:grief_seed;1;false;1", "10;yuusha:grief_seed;1;false;1", "11;yuusha:grief_seed;1;false;1", "12;yuusha:grief_seed;1;false;1"]
	#Set to true to scale amount of loot drops from champions to tier if sourced from config
	lootScaling = false

[growth]
	#The percent increase in health multiplied by the growth factor
	#Range: 0.0 ~ 1.7976931348623157E308
	healthGrowth = 1.0
	#The percent increase in attack damage multiplied by the growth factor
	#Range: 0.0 ~ 1.7976931348623157E308
	attackGrowth = 0.1
	#The increase in armor multiplied by the growth factor
	#Range: 0.0 ~ 30.0
	armorGrowth = 1.0
	#The increase in armor toughness multiplied by the growth factor
	#Range: 0.0 ~ 30.0
	toughnessGrowth = 0.75
	#The increase in knockback resistance multiplied by the growth factor
	#Range: 0.0 ~ 1.0
	knockbackResistanceGrowth = 0.01
	#The increase in experience multiplied by the growth factor
	#Range: > 0
	experienceGrowth = 0.5
	#The increase in explosive range multiplied by the growth factor
	#Range: 0 ~ 100
	explosionGrowth = 0

[affixes]
	#Set the maximum distance that mobs can use their targeted abilities from, 0 to disable
	#Range: 0.0 ~ 100.0
	affixTargetRange = 0.0

	[affixes.adaptable]
		#The increase in damage reduction for each consecutive attack of the same damage type
		#Range: 0.0 ~ 1.0
		adaptableDamageReductionIncrement = 0.45
		#The maximum damage reduction
		#Range: 0.0 ~ 1.0
		adaptableMaxDamageReduction = 0.9

	[affixes.arctic]
		#How often the champion will shoot projectiles (in seconds)
		#Range: 1 ~ 100
		arcticAttackInterval = 1

	[affixes.dampened]
		#The amount of damage reduction to apply to indirect attacks
		#Range: 0.0 ~ 1.0
		dampenedDamageReduction = 0.5

	[affixes.desecrating]
		#How long (in seconds) between cloud placements
		#Range: > 1
		desecratingCloudInterval = 3
		#How long (in seconds) it takes for the effect cloud to activate after being placed
		#Range: > 0
		desecratingCloudActivationTime = 2
		#The radius of the cloud effect
		#Range: 1.0 ~ 1.7976931348623157E308
		desecratingCloudRadius = 4.0
		#The duration (in seconds) of the cloud effect
		#Range: > 1
		desecratingCloudDuration = 10

	[affixes.enkindling]
		#How often the champion will shoot projectiles (in seconds)
		#Range: 1 ~ 100
		enkindlingAttackInterval = 1

	[affixes.hasty]
		#The base movement speed bonus
		#Range: 0.0 ~ 1.7976931348623157E308
		hastyMovementBonus = 0.1

	[affixes.infested]
		#The amount of parasites to spawn per interval
		#Range: 1 ~ 100
		infestedAmount = 2
		#The time (in seconds) between parasite spawns
		#Range: 1 ~ 100
		infestedInterval = 3
		#The amount of parasites to infest per health point of the champion
		#Range: 0.0 ~ 1.7976931348623157E308
		infestedPerHealth = 0.5
		#The total amount of parasites a champion can house at once
		#Range: > 1
		infestedTotal = 4
		#The mob to use as a parasite for infestation
		infestedParasite = "minecraft:silverfish"
		#The mob to use as a parasite for infestation of ender mob
		infestedEnderParasite = "minecraft:endermite"

	[affixes.paralyzing]
		#The percent chance that an attack will paralyze targets
		#Range: 0.0 ~ 1.0
		paralyzingChance = 0.10

	[affixes.knocking]
		#The multiplier to apply to the knockback strength
		#Range: 0.0 ~ 1.7976931348623157E308
		knockingMultiplier = 10.0

	[affixes.lively]
		#The amount of health per second regeneration
		#Range: 0.0 ~ 1.7976931348623157E308
		livelyHealAmount = 10000.0
		#Multiplier to health regeneration when not aggressive
		#Range: 1.0 ~ 1.7976931348623157E308
		livelyPassiveMultiplier = 100.0
		#Set cooldown (in seconds) for regeneration after getting attacked
		#Range: > 1
		livelyCooldown = 5

	[affixes.molten]
		#Set to true to have Molten champions not be damaged by water
		moltenWaterResistance = true

	[affixes.plagued]
		#The effect that will be spread
		#Format:[effect];[power];[duration(secs)]
		plaguedEffect = "goety:plunge;15;2"
		#The range of the plagued effect
		#Range: 1 ~ 100
		plaguedRange = 6

	[affixes.reflective]
		#The minimum percent of damage to reflect back
		#Range: 0.0 ~ 1.0
		reflectiveMinPercent = 0.1
		#The maximum percent of damage to reflect back
		#Range: 0.0 ~ 1.0
		reflectiveMaxPercent = 0.15
		#The maximum amount of damage to reflect back
		#Range: > 0
		reflectiveMax = 1000
		#Set to true to enable deadly reflected strikes
		reflectiveLethal = false

	[affixes.magnetic]
		#Strength of the magnetic pulling effect
		#Range: 0.0 ~ 100.0
		magneticStrength = 0.075

	[affixes.wounding]
		#The percent chance that an attack will wound targets
		#Range: 0.0 ~ 1.0
		woundingChance = 0.8

[integrations]
	#Scaling Health
	#List of tiers with numbers to multiply spawn rates by difficulty
	#Format: [tier];[percent increase]
	scalingHealthSpawnModifiers = []

