
#Dark Doppelganger Configuration
[dark_doppelganger]
	#Health of the Dark Doppelganger
	#Range: 1.0 ~ 100000.0
	health = 38500.0
	#Attack Damage of the Dark Doppelganger
	#Range: 1.0 ~ 100.0
	attack_damage = 100.0
	#Movement Speed of the Dark Doppelganger
	#Range: 0.1 ~ 1.0
	movement_speed = 0.2
	#Knockback Resistance of the Dark Doppelganger
	#Range: 0.0 ~ 1.0
	knockback_resistance = 1.0
	#Armor of the Dark Doppelganger
	#Range: 0.0 ~ 100.0
	armor = 100.0
	#Follow Range of the Dark Doppelganger
	#Range: 1.0 ~ 128.0
	follow_range = 64.0
	#Hard mode of the Dark Doppelganger
	hard_mode = true
	#List of banned armor items (format: modid:item_name or modid:* for full mod) that should not be copied to the Dark Doppelganger
	banned_armor = ["cataclysm:cursium_helmet", "cataclysm:cursium_chestplate", "cataclysm:cursium_leggings", "cataclysm:cursium_boots", "mycoolmod:*"]
	#List of all spells the Dark Doppelganger can use in the final phase (Hard mode must be enabled for custom spell usage ( TO works !))
	final_phase_spells = ["irons_spellbooks:eldritch_blast", "irons_spellbooks:sonic_boom", "irons_spellbooks:sculk_tentacles", "irons_spellbooks:root", "irons_spellbooks:ray_of_frost", "irons_spellbooks:earthquake", "irons_spellbooks:sunbeam", "irons_spellbooks:ball_lightning", "irons_spellbooks:black_hole", "irons_spellbooks:ray_of_siphoning", "irons_spellbooks:scorch", "irons_spellbooks:firecracker", "refined_mod:moon_slash"]

