
[ShieldList]
	#
	#List of items to considered as shields, any item with right-click functionality will theoretically work
	#Automatically populated with items that have parrying stats set by active datapacks
	shieldList = ["shieldexp:wooden_shield", "shieldexp:griefer_shield", "shieldexp:iron_shield", "shieldexp:netherite_shield", "stalwart_dungeons:tungsten_shield", "minecraft:shield", "shieldexp:golden_shield", "stalwart_dungeons:chorundum_shield", "shieldexp:diamond_shield", "shieldexp:paragon_shield", "stalwart_dungeons:warted_tungsten_shield", "artifacts:umbrella", "enigmaticlegacy:infernal_shield", "forbidden_arcanus:obsidian_skull_shield", "cataclysm:bulwark_of_the_flame", "bygonenether:gilded_netherite_shield", "cataclysm:black_steel_targe", "hmag:ancient_shield", "grimoireofgaia:bone_shield", "grimoireofgaia:stone_shield", "grimoireofgaia:gold_shield", "grimoireofgaia:iron_shield", "hmag:fortress_shield", "deep_aether:skyjade_shield", "lost_aether_content:shield_of_emile", "lost_aether_content:zanite_shield", "deep_aether:stratus_shield", "lost_aether_content:gravitite_shield"]
	#
	#List of items to not consider as shields, even if they have stats set by a datapack
	shieldBlacklist = []

[Modifiers]
	#
	#Disable the cooldown when the player lowers their shield
	noLoweringCooldown = true
	#
	#Disable putting shields on cooldown at all
	noCooldown = false
	#
	#Make all shields have vanilla movement speed
	noSpeedModifier = false
	#
	#Make shields only block partial damage from explosions when not parrying
	harderExplosions = false
	#
	#Double the parry window for a more relaxed experience
	lenientParryMode = false
	#
	#Double the shield stamina for a more relaxed experience
	lenientStaminaMode = false

